import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type Language = "en" | "fr" | "es" | "it";

export const languages: { code: Language; label: string; short: string }[] = [
  { code: "en", label: "English", short: "EN" },
  { code: "fr", label: "Français", short: "FR" },
  { code: "es", label: "Español", short: "ES" },
  { code: "it", label: "Italiano", short: "IT" },
];

type Dictionary = Record<string, string>;

const dictionaries: Record<Language, Dictionary> = {
  en: {
    "nav.home": "Home", "nav.shop": "Shop", "nav.about": "About", "nav.blog": "Journal", "nav.contact": "Contact", "nav.cart": "Cart", "nav.menu": "Menu",
    "home.eyebrow": "The 2026 Collection", "home.titleA": "Tools forged for the", "home.titleB": "masters", "home.titleC": "of the chair.", "home.copy": "Hand-engineered in limited series. Aerospace alloys, Japanese steel, surgical motors. Built for those who refuse compromise.", "home.shop": "Shop Collection", "home.craft": "Our Craft", "home.stat1": "Years of craft", "home.stat2": "Countries served", "home.stat3": "Lifetime warranty", "home.explore": "Explore", "home.collection": "The Collection", "home.viewAll": "View all", "home.signature": "Signature", "home.featured": "Featured Pieces", "home.cardExplore": "Explore", "home.innovation": "Innovation", "home.design": "Design", "home.performance": "Performance", "home.innovationText": "Brushless motors, smart sensors, and aerospace alloys engineered with the world's leading material scientists.", "home.designText": "Form follows ritual. Every curve, weight and detail considered for hours of use, not minutes of impression.", "home.performanceText": "Built to be owned for life. Maintained, sharpened and repaired in our atelier — never replaced.",
    "products.shop": "Shop", "products.title": "The Atelier Collection", "products.copy": "Each piece engineered, balanced and tested to elevate your craft.", "products.category": "Category", "products.color": "Color", "products.clearColor": "Clear color", "products.priceRange": "Price Range", "products.filters": "Filters", "products.close": "Close", "products.piece": "piece", "products.pieces": "pieces", "products.empty": "No products match your filters.", "products.sortFeatured": "Sort: Featured", "products.sortAsc": "Price: Low to High", "products.sortDesc": "Price: High to Low", "products.quickAdd": "Quick add", "products.added": "added", "products.colorLabel": "Color",
    "detail.notFound": "Piece not found", "detail.backCollection": "Back to collection", "detail.backCollectionCaps": "Back to Collection", "detail.color": "Color", "detail.decrease": "Decrease", "detail.increase": "Increase", "detail.addBag": "Add to Bag", "detail.addedBag": "added to bag", "detail.qty": "Qty", "detail.detail": "The Detail", "detail.specs": "Specifications", "detail.included": "Included", "detail.promise": "The Atelier Promise", "detail.related": "You may also like",
    "cart.emptyTitle": "Your bag is empty", "cart.emptyCopy": "Begin curating your atelier.", "cart.explore": "Explore the Collection", "cart.yourBag": "Your Bag", "cart.checkout": "Checkout", "cart.clear": "Clear bag", "cart.summary": "Order Summary", "cart.subtotal": "Subtotal", "cart.shipping": "Shipping", "cart.free": "Complimentary", "cart.total": "Total", "cart.proceed": "Proceed to Checkout", "cart.secure": "Secure payment · Lifetime warranty", "cart.remove": "Remove",
    "contact.label": "Contact", "contact.title": "Speak with the atelier", "contact.copy": "Our concierge team responds within 4 hours, 24 hours a day, in 12 languages.", "contact.name": "Name", "contact.email": "Email", "contact.message": "Message", "contact.send": "Send Message", "contact.received": "Message received", "contact.response": "Our concierge will respond within 4 hours.", "contact.atelier": "The Atelier", "contact.visit": "Visit by appointment",
    "blog.label": "Journal", "blog.title": "Notes from the workshop", "blog.copy": "Interviews, techniques and reflections from the craftsmen and stylists who shape our work.", "blog.read": "Read",
    "about.label": "Our Story", "about.titleA": "Engineered for those who", "about.titleB": "refuse", "about.titleC": "compromise.", "about.copy": "LUXE Atelier was founded in 2014 by a third-generation barber and an aerospace engineer. We were tired of tools designed for spreadsheets, not for the hand. So we built our own.", "about.quote": "A great tool is not a purchase. It is a partnership for the length of a career.", "about.founder": "— Marco Verdi, Founder",
    "footer.copy": "Engineered for the world's finest barbers and stylists. Crafted in limited series. Owned for a lifetime.", "footer.shop": "Shop", "footer.all": "All Products", "footer.house": "House", "footer.story": "Our Story", "footer.connect": "Connect", "footer.rights": "All rights reserved.", "footer.crafted": "Crafted with obsessive precision.",
    "cat.all": "All Products", "cat.Clippers": "Clippers", "cat.Hairdryers": "Hairdryers", "cat.Trimmers": "Trimmers", "cat.Straighteners": "Straighteners", "cat.Curling Tools": "Curling Tools", "cat.Accessories": "Accessories",
  },
  fr: {
    "nav.home": "Accueil", "nav.shop": "Boutique", "nav.about": "Maison", "nav.blog": "Journal", "nav.contact": "Contact", "nav.cart": "Panier", "nav.menu": "Menu",
    "home.eyebrow": "Collection 2026", "home.titleA": "Des outils forgés pour les", "home.titleB": "maîtres", "home.titleC": "du fauteuil.", "home.copy": "Conçus à la main en séries limitées. Alliages aéronautiques, acier japonais, moteurs chirurgicaux. Pour ceux qui refusent le compromis.", "home.shop": "Voir la collection", "home.craft": "Notre savoir-faire", "home.stat1": "Années de métier", "home.stat2": "Pays servis", "home.stat3": "Garantie à vie", "home.explore": "Explorer", "home.collection": "La Collection", "home.viewAll": "Tout voir", "home.signature": "Signature", "home.featured": "Pièces vedettes", "home.cardExplore": "Explorer", "home.innovation": "Innovation", "home.design": "Design", "home.performance": "Performance", "home.innovationText": "Moteurs brushless, capteurs intelligents et alliages aéronautiques développés avec des spécialistes des matériaux.", "home.designText": "La forme suit le rituel. Chaque courbe, poids et détail est pensé pour des heures d'utilisation.", "home.performanceText": "Créés pour durer une vie. Entretenus, affûtés et réparés dans notre atelier — jamais remplacés.",
    "products.shop": "Boutique", "products.title": "La Collection Atelier", "products.copy": "Chaque pièce est conçue, équilibrée et testée pour élever votre art.", "products.category": "Catégorie", "products.color": "Couleur", "products.clearColor": "Effacer la couleur", "products.priceRange": "Gamme de prix", "products.filters": "Filtres", "products.close": "Fermer", "products.piece": "pièce", "products.pieces": "pièces", "products.empty": "Aucun produit ne correspond à vos filtres.", "products.sortFeatured": "Tri : vedettes", "products.sortAsc": "Prix : croissant", "products.sortDesc": "Prix : décroissant", "products.quickAdd": "Ajout rapide", "products.added": "ajouté", "products.colorLabel": "Couleur",
    "detail.notFound": "Pièce introuvable", "detail.backCollection": "Retour à la collection", "detail.backCollectionCaps": "Retour à la collection", "detail.color": "Couleur", "detail.decrease": "Diminuer", "detail.increase": "Augmenter", "detail.addBag": "Ajouter au panier", "detail.addedBag": "ajouté au panier", "detail.qty": "Qté", "detail.detail": "Le détail", "detail.specs": "Spécifications", "detail.included": "Inclus", "detail.promise": "La promesse Atelier", "detail.related": "Vous aimerez aussi",
    "cart.emptyTitle": "Votre panier est vide", "cart.emptyCopy": "Commencez à composer votre atelier.", "cart.explore": "Explorer la collection", "cart.yourBag": "Votre panier", "cart.checkout": "Commande", "cart.clear": "Vider le panier", "cart.summary": "Résumé de commande", "cart.subtotal": "Sous-total", "cart.shipping": "Livraison", "cart.free": "Offerte", "cart.total": "Total", "cart.proceed": "Passer la commande", "cart.secure": "Paiement sécurisé · Garantie à vie", "cart.remove": "Supprimer",
    "contact.label": "Contact", "contact.title": "Parlez avec l'atelier", "contact.copy": "Notre conciergerie répond sous 4 heures, 24h/24, en 12 langues.", "contact.name": "Nom", "contact.email": "Email", "contact.message": "Message", "contact.send": "Envoyer", "contact.received": "Message reçu", "contact.response": "Notre conciergerie répondra sous 4 heures.", "contact.atelier": "L'Atelier", "contact.visit": "Visite sur rendez-vous",
    "blog.label": "Journal", "blog.title": "Notes de l'atelier", "blog.copy": "Entretiens, techniques et réflexions des artisans et stylistes qui façonnent notre travail.", "blog.read": "Lire",
    "about.label": "Notre histoire", "about.titleA": "Conçu pour ceux qui", "about.titleB": "refusent", "about.titleC": "le compromis.", "about.copy": "LUXE Atelier a été fondé en 2014 par un barbier de troisième génération et un ingénieur aéronautique. Lassés des outils pensés pour les tableaux, pas pour la main, nous avons créé les nôtres.", "about.quote": "Un grand outil n'est pas un achat. C'est un partenariat pour toute une carrière.", "about.founder": "— Marco Verdi, Fondateur",
    "footer.copy": "Conçu pour les meilleurs barbiers et stylistes du monde. Fabriqué en séries limitées. Possédé pour la vie.", "footer.shop": "Boutique", "footer.all": "Tous les produits", "footer.house": "Maison", "footer.story": "Notre histoire", "footer.connect": "Réseaux", "footer.rights": "Tous droits réservés.", "footer.crafted": "Façonné avec une précision obsessionnelle.",
    "cat.all": "Tous les produits", "cat.Clippers": "Tondeuses", "cat.Hairdryers": "Sèche-cheveux", "cat.Trimmers": "Tondeuses de précision", "cat.Straighteners": "Lisseurs", "cat.Curling Tools": "Fers à boucler", "cat.Accessories": "Accessoires",
  },
  es: {
    "nav.home": "Inicio", "nav.shop": "Tienda", "nav.about": "Marca", "nav.blog": "Diario", "nav.contact": "Contacto", "nav.cart": "Carrito", "nav.menu": "Menú",
    "home.eyebrow": "Colección 2026", "home.titleA": "Herramientas forjadas para los", "home.titleB": "maestros", "home.titleC": "del sillón.", "home.copy": "Diseñadas a mano en series limitadas. Aleaciones aeroespaciales, acero japonés y motores quirúrgicos. Para quienes no aceptan compromisos.", "home.shop": "Ver colección", "home.craft": "Nuestro oficio", "home.stat1": "Años de oficio", "home.stat2": "Países atendidos", "home.stat3": "Garantía de por vida", "home.explore": "Explorar", "home.collection": "La Colección", "home.viewAll": "Ver todo", "home.signature": "Signature", "home.featured": "Piezas destacadas", "home.cardExplore": "Explorar", "home.innovation": "Innovación", "home.design": "Diseño", "home.performance": "Rendimiento", "home.innovationText": "Motores sin escobillas, sensores inteligentes y aleaciones aeroespaciales creadas con expertos en materiales.", "home.designText": "La forma sigue al ritual. Cada curva, peso y detalle está pensado para horas de uso.", "home.performanceText": "Hechas para durar toda la vida. Mantenidas, afiladas y reparadas en nuestro atelier — nunca reemplazadas.",
    "products.shop": "Tienda", "products.title": "La Colección Atelier", "products.copy": "Cada pieza está diseñada, equilibrada y probada para elevar tu oficio.", "products.category": "Categoría", "products.color": "Color", "products.clearColor": "Borrar color", "products.priceRange": "Rango de precio", "products.filters": "Filtros", "products.close": "Cerrar", "products.piece": "pieza", "products.pieces": "piezas", "products.empty": "Ningún producto coincide con tus filtros.", "products.sortFeatured": "Orden: destacados", "products.sortAsc": "Precio: menor a mayor", "products.sortDesc": "Precio: mayor a menor", "products.quickAdd": "Añadir rápido", "products.added": "añadido", "products.colorLabel": "Color",
    "detail.notFound": "Pieza no encontrada", "detail.backCollection": "Volver a la colección", "detail.backCollectionCaps": "Volver a la colección", "detail.color": "Color", "detail.decrease": "Disminuir", "detail.increase": "Aumentar", "detail.addBag": "Añadir al carrito", "detail.addedBag": "añadido al carrito", "detail.qty": "Cant.", "detail.detail": "El detalle", "detail.specs": "Especificaciones", "detail.included": "Incluido", "detail.promise": "La promesa Atelier", "detail.related": "También te puede gustar",
    "cart.emptyTitle": "Tu carrito está vacío", "cart.emptyCopy": "Empieza a curar tu atelier.", "cart.explore": "Explorar la colección", "cart.yourBag": "Tu carrito", "cart.checkout": "Checkout", "cart.clear": "Vaciar carrito", "cart.summary": "Resumen del pedido", "cart.subtotal": "Subtotal", "cart.shipping": "Envío", "cart.free": "Gratis", "cart.total": "Total", "cart.proceed": "Continuar al pago", "cart.secure": "Pago seguro · Garantía de por vida", "cart.remove": "Eliminar",
    "contact.label": "Contacto", "contact.title": "Habla con el atelier", "contact.copy": "Nuestro equipo concierge responde en 4 horas, 24 horas al día, en 12 idiomas.", "contact.name": "Nombre", "contact.email": "Email", "contact.message": "Mensaje", "contact.send": "Enviar mensaje", "contact.received": "Mensaje recibido", "contact.response": "Nuestro concierge responderá en 4 horas.", "contact.atelier": "El Atelier", "contact.visit": "Visita con cita previa",
    "blog.label": "Diario", "blog.title": "Notas del taller", "blog.copy": "Entrevistas, técnicas y reflexiones de los artesanos y estilistas que dan forma a nuestro trabajo.", "blog.read": "Leer",
    "about.label": "Nuestra historia", "about.titleA": "Diseñado para quienes", "about.titleB": "rechazan", "about.titleC": "el compromiso.", "about.copy": "LUXE Atelier fue fundado en 2014 por un barbero de tercera generación y un ingeniero aeroespacial. Cansados de herramientas pensadas para hojas de cálculo, no para la mano, construimos las nuestras.", "about.quote": "Una gran herramienta no es una compra. Es una alianza para toda una carrera.", "about.founder": "— Marco Verdi, Fundador",
    "footer.copy": "Diseñado para los mejores barberos y estilistas del mundo. Creado en series limitadas. Propiedad para toda la vida.", "footer.shop": "Tienda", "footer.all": "Todos los productos", "footer.house": "Marca", "footer.story": "Nuestra historia", "footer.connect": "Conectar", "footer.rights": "Todos los derechos reservados.", "footer.crafted": "Creado con precisión obsesiva.",
    "cat.all": "Todos los productos", "cat.Clippers": "Cortadoras", "cat.Hairdryers": "Secadores", "cat.Trimmers": "Perfiladoras", "cat.Straighteners": "Planchas", "cat.Curling Tools": "Rizadores", "cat.Accessories": "Accesorios",
  },
  it: {
    "nav.home": "Home", "nav.shop": "Shop", "nav.about": "Storia", "nav.blog": "Journal", "nav.contact": "Contatti", "nav.cart": "Carrello", "nav.menu": "Menu",
    "home.eyebrow": "Collezione 2026", "home.titleA": "Strumenti forgiati per i", "home.titleB": "maestri", "home.titleC": "della poltrona.", "home.copy": "Ingegnerizzati a mano in serie limitate. Leghe aerospaziali, acciaio giapponese, motori chirurgici. Per chi rifiuta il compromesso.", "home.shop": "Scopri la collezione", "home.craft": "Il nostro mestiere", "home.stat1": "Anni di mestiere", "home.stat2": "Paesi serviti", "home.stat3": "Garanzia a vita", "home.explore": "Esplora", "home.collection": "La Collezione", "home.viewAll": "Vedi tutto", "home.signature": "Signature", "home.featured": "Pezzi in evidenza", "home.cardExplore": "Esplora", "home.innovation": "Innovazione", "home.design": "Design", "home.performance": "Performance", "home.innovationText": "Motori brushless, sensori intelligenti e leghe aerospaziali sviluppate con esperti dei materiali.", "home.designText": "La forma segue il rituale. Ogni curva, peso e dettaglio è pensato per ore di utilizzo.", "home.performanceText": "Costruiti per durare una vita. Manutenuti, affilati e riparati nel nostro atelier — mai sostituiti.",
    "products.shop": "Shop", "products.title": "La Collezione Atelier", "products.copy": "Ogni pezzo è progettato, bilanciato e testato per elevare il tuo mestiere.", "products.category": "Categoria", "products.color": "Colore", "products.clearColor": "Cancella colore", "products.priceRange": "Fascia prezzo", "products.filters": "Filtri", "products.close": "Chiudi", "products.piece": "pezzo", "products.pieces": "pezzi", "products.empty": "Nessun prodotto corrisponde ai filtri.", "products.sortFeatured": "Ordina: in evidenza", "products.sortAsc": "Prezzo: crescente", "products.sortDesc": "Prezzo: decrescente", "products.quickAdd": "Aggiunta rapida", "products.added": "aggiunto", "products.colorLabel": "Colore",
    "detail.notFound": "Pezzo non trovato", "detail.backCollection": "Torna alla collezione", "detail.backCollectionCaps": "Torna alla collezione", "detail.color": "Colore", "detail.decrease": "Diminuisci", "detail.increase": "Aumenta", "detail.addBag": "Aggiungi al carrello", "detail.addedBag": "aggiunto al carrello", "detail.qty": "Qtà", "detail.detail": "Il dettaglio", "detail.specs": "Specifiche", "detail.included": "Incluso", "detail.promise": "La promessa Atelier", "detail.related": "Potrebbe piacerti anche",
    "cart.emptyTitle": "Il carrello è vuoto", "cart.emptyCopy": "Inizia a curare il tuo atelier.", "cart.explore": "Esplora la collezione", "cart.yourBag": "Il tuo carrello", "cart.checkout": "Checkout", "cart.clear": "Svuota carrello", "cart.summary": "Riepilogo ordine", "cart.subtotal": "Subtotale", "cart.shipping": "Spedizione", "cart.free": "Omaggio", "cart.total": "Totale", "cart.proceed": "Procedi al checkout", "cart.secure": "Pagamento sicuro · Garanzia a vita", "cart.remove": "Rimuovi",
    "contact.label": "Contatti", "contact.title": "Parla con l'atelier", "contact.copy": "Il nostro team concierge risponde entro 4 ore, 24 ore su 24, in 12 lingue.", "contact.name": "Nome", "contact.email": "Email", "contact.message": "Messaggio", "contact.send": "Invia messaggio", "contact.received": "Messaggio ricevuto", "contact.response": "Il nostro concierge risponderà entro 4 ore.", "contact.atelier": "L'Atelier", "contact.visit": "Visita su appuntamento",
    "blog.label": "Journal", "blog.title": "Note dal laboratorio", "blog.copy": "Interviste, tecniche e riflessioni dagli artigiani e stylist che modellano il nostro lavoro.", "blog.read": "Leggi",
    "about.label": "La nostra storia", "about.titleA": "Progettato per chi", "about.titleB": "rifiuta", "about.titleC": "il compromesso.", "about.copy": "LUXE Atelier nasce nel 2014 da un barbiere di terza generazione e un ingegnere aerospaziale. Stanchi di strumenti pensati per i fogli di calcolo, non per la mano, abbiamo creato i nostri.", "about.quote": "Un grande strumento non è un acquisto. È una partnership per tutta una carriera.", "about.founder": "— Marco Verdi, Fondatore",
    "footer.copy": "Progettato per i migliori barbieri e stylist del mondo. Creato in serie limitate. Posseduto per una vita.", "footer.shop": "Shop", "footer.all": "Tutti i prodotti", "footer.house": "Casa", "footer.story": "La nostra storia", "footer.connect": "Connetti", "footer.rights": "Tutti i diritti riservati.", "footer.crafted": "Creato con precisione ossessiva.",
    "cat.all": "Tutti i prodotti", "cat.Clippers": "Tagliacapelli", "cat.Hairdryers": "Asciugacapelli", "cat.Trimmers": "Rifinitori", "cat.Straighteners": "Piastre", "cat.Curling Tools": "Arricciacapelli", "cat.Accessories": "Accessori",
  },
};

type LanguageContextValue = { language: Language; setLanguage: (language: Language) => void; t: (key: string) => string; category: (key: string) => string };

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const saved = window.localStorage.getItem("luxe-language") as Language | null;
    if (saved && languages.some((l) => l.code === saved)) setLanguageState(saved);
  }, []);

  const setLanguage = (next: Language) => {
    setLanguageState(next);
    window.localStorage.setItem("luxe-language", next);
    document.documentElement.lang = next;
  };

  const value = useMemo(() => ({
    language,
    setLanguage,
    t: (key: string) => dictionaries[language][key] ?? dictionaries.en[key] ?? key,
    category: (key: string) => dictionaries[language][`cat.${key}`] ?? key,
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used inside LanguageProvider");
  return context;
}